# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/szar/drexel/2017-fall/ecec661/bubble-sort/bubble_sort/bubble_sort.cache/wt [current_project]
set_property parent.project_path /home/szar/drexel/2017-fall/ecec661/bubble-sort/bubble_sort/bubble_sort.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo /home/szar/drexel/2017-fall/ecec661/bubble-sort/bubble_sort/bubble_sort.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/szar/drexel/2017-fall/ecec661/bubble-sort/processing_element.vhd
  /home/szar/drexel/2017-fall/ecec661/bubble-sort/array_sorter.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top array_sorter -part xc7z010clg400-1


write_checkpoint -force -noxdef array_sorter.dcp

catch { report_utilization -file array_sorter_utilization_synth.rpt -pb array_sorter_utilization_synth.pb }
